# Generated by Django 4.0.3 on 2022-05-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFavorites',
        ),
    ]
