# Generated by Django 4.0.3 on 2022-05-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favmovies',
            name='poster_img',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
