# Generated by Django 4.0.3 on 2022-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0004_favmovies_poster_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='favmovies',
            name='pfp_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
