# Generated by Django 4.0.3 on 2022-05-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0005_favmovies_pfp_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favmovies',
            name='pfp_img',
        ),
    ]
