# Generated by Django 4.0.3 on 2022-05-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0008_rename_profiledetails_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
