# Generated by Django 4.0.3 on 2022-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0011_profiledetails_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
