# Generated by Django 4.0.3 on 2022-05-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0013_alter_profiledetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pfp/default.jpg', null=True, upload_to=''),
        ),
    ]
