# Generated by Django 4.0.3 on 2022-06-03 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dreamstream', '0015_alter_profiledetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pfp/'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
