# Generated by Django 4.0.3 on 2022-06-03 20:18

from django.db import migrations, models
import user_dreamstream.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_dreamstream', '0016_alter_profiledetails_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pfp/', validators=[user_dreamstream.validators.image_restrictions]),
        ),
    ]
